// auth
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const RESET_ON_FAILED_REGISTER = "RESET_ON_FAILED_REGISTER";

export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const RESET_ON_FAILED_LOGIN = "RESET_ON_FAILED_LOGIN";

export const UPDATE_USER = "UPDATE_USER";

// shifts
export const ADDING_SHIFT = "ADDING_SHIFT";
export const SET_SHIFT_MSG = "SET_SHIFT_MSG"
export const ADDED_SHIFT_SUCCESSFUL = "ADDED_SHIFT_SUCCESSFUL";
export const ADDED_SHIFT_FAILURE = "ADDED_SHIFT_FAILURE";

// inventory
export const UPDATE_INVENTORY = "UPDATE_INVENTORY"
export const UPDATE_INVENOTRY_ERR = "UPDATE_INVENTORY_ERR"
export const GET_INVENTORY = "GET_INVENTORY"
export const GET_INVENTORY_ERR = "GET_INVENTORY_ERR"
export const GET_ITEM = "GET_ITEM"
export const GET_ITEM_ERR = "GET_ITEM_ERR"