// auth
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const RESET_ON_FAILED_REGISTER = "RESET_ON_FAILED_REGISTER";

export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const RESET_ON_FAILED_LOGIN = "RESET_ON_FAILED_LOGIN";

export const LOGOUT_USER = "LOGOUT_USER";

// shifts
export const ADDING_SHIFT_FAIL = "ADDING_SHIFT_FAIL";
export const ADDING_SHIFT_SUCCESS = "ADDING_SHIFT_SUCCESS";
export const RESET_ON_FAILED_SHIFT_ADD = "RESET_ON_FAILED_SHIFT_ADD";

export const DELETING_SHIFT_FAIL = "DELETING_SHIFT_FAIL";
export const DELETING_SHIFT_SUCCESS = "DELETING_SHIFT_SUCCESS";
export const RESET_ON_FAILED_SHIFT_DELETE = "RESET_ON_FAILED_SHIFT_DELETE";
export const UPDATE_USER = "UPDATE_USER";

// inventory
export const UPDATE_INVENTORY = "UPDATE_INVENTORY"
export const UPDATE_INVENOTRY_ERR = "UPDATE_INVENTORY_ERR"
export const GET_INVENTORY = "GET_INVENTORY"
export const GET_INVENTORY_ERR = "GET_INVENTORY_ERR"
export const GET_ITEM = "GET_ITEM"
export const GET_ITEM_ERR = "GET_ITEM_ERR"

// orders
export const GET_IN_ORDERS = "GET_IN_ORDERS";
export const GET_IN_ORDERS_ERR = "GET_IN_ORDERS_ERR";
export const GET_OUT_ORDERS = "GET_OUT_ORDERS";
export const GET_OUT_ORDERS_ERR = "GET_OUT_ORDERS_ERR"


// users
export const GET_NUM_OF_USERS = "GET_NUM_OF_USERS";